### ISSUE TITLE
It killed my pc. How do i fix this?

### ISSUE THREAD

**Issue by ItsLap** [alexfeed1990/filetrasher#1]

**Comment by datkat21** [comment]
wait did you actually run it

**Comment by alexfeed1990** [comment]
If you considered that running this on you're host machine will result into **nothing**, then im sorry to say but you are a _idiot._

In further assistance, what folder did you run the program in? Did you run it as administrator/TrustedInstaller? If you have ran the program in the root of C: and you have ran it as admin, congratulations! You have trahsed **_all_** of you're files!  (actually im prrtty sorry and this was supposed to be a test. If you go in a windows PE boot disk you will find that most files only contain "Trashed by filetrasher XD" so yeah..)

**Comment by datkat21** [comment]
See title of 43a0d6975c8dbcf1b36c5e95e08907af2fd5e66c &mdash; it says to run it and break your PC which is not a very good idea.

**Comment by alexfeed1990** [comment]
> See title of 43a0d6975c8dbcf1b36c5e95e08907af2fd5e66c &mdash; it says to run it and break your PC which is not a very good idea.

it says to run it in c: and as administrator to destroy windows, as a choice.
